### PR TITLE
Task 10785 : Static pages

### PR DESCRIPTION
**Pull request by doanhoangvu98**

### CODE REVIEW

**Comment by doanhoangvu98** [comment]
Screenshot from 2019-04-17 13-09-28
https://edu-redmine.sun-asterisk.vn/issues/10785

**Comment by doanhoangvu98** [comment]
ready

**Comment by huynhlv** [comment]
fix 3 commit kìa e

**Comment by VuThiTranVan** [comment]
commented
fix 3 commit kìa e
bạn comment mà hơm fix ah (kill)

**Pull request closed without merging**
